name: tiny_dialog
description: "Very Easy Simple Dialog for Flutter"
version: 1.0.0
homepage: "https://axemma.my.id"

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
